esphome:
  name: oled

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""
    on_progress:
      then:
        - lambda: |-
            id(ota_progress) = x;  // store progress percentage
            // id(oled_id).update();
        - display.page.show: oled_ota_page
wifi:
  ssid: "home"
  password: "darkmaster"
  min_auth_mode: WPA2
  ap: {}

captive_portal:
web_server:
i2c:
  frequency: 100khz
  
globals:
  - id: flag
    type: bool
    initial_value: 'false'

  - id: ota_progress
    type: float
    restore_value: no
    initial_value: "0"
    
font:
  - file: "gfonts://Roboto"
    id: font1
    size: 14
  - file: "gfonts://Roboto"
    id: font2
    size: 42
  - file: "gfonts://Roboto"
    id: font3
    size: 24

image:
  defaults:
    type: binary
    resize: 128x64
  images:
    - file: "WTLC/logo.png"
      id: logo
    - file: "WTLC/alert.png"
      id: alert

display:
  - platform: ssd1306_i2c
    model: SSD1306_128X64
    id: oled_id
    pages:
      - id: alert_page
        lambda: |-
          it.image(0, 0, id(alert));

      - id: check
        lambda: |-
          it.clear();
          it.printf(5 , 5, id(font1), id(flag)? "Hello" : "Hii");

      - id: oled_ota_page
        lambda: |-
          float p = id(ota_progress);
          if (p < 0 || p > 100) p = 0;
          it.printf(05, 0, id(font1), "UPDATING: %0.0f%%", p);
          it.rectangle(05, 20, it.get_width() - 10, 20);
          int bar_width = (int)((it.get_width() - 12) * p / 100.0f);
          it.filled_rectangle(6, 21, bar_width, 18);

interval:
  - interval: 1s
    id: change_id
    then:
      - lambda: |-
          id(flag) = !id(flag);
          id(oled_id).update();