esphome:
  name: bedroom-2-motion
  friendly_name: Bedroom 2
  area: Bedroom 2
  comment: "Motion Sensor"
  project:
    name: "MDtronix.Motion"
    version: "1.0"

esp32:
  board: seeed_xiao_esp32c3
  variant: ESP32C3
  framework:
    type: arduino

# esp8266:
#   board: d1_mini

uart:
  id: ld2420_radar
  tx_pin: 5
  rx_pin: 4
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

i2c:
  id: temp_comm_ID
  sda: 7
  scl: 6
  scan: True
  
logger:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}
  min_auth_mode: WPA2
  
captive_portal:
web_server:
  version: 3


ld2420:
  
text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

sensor:
  - platform: ld2420
    moving_distance:
      name : Moving Distance
      
  - platform: aht10
    variant: AHT20
    temperature: 
      name: Temperature
      accuracy_decimals: 0
      # filters: 
      #   - calibrate_linear:
      #       - 0.0 -> 0.0
    humidity: 
      name: Humidity
      accuracy_decimals: 0
    update_interval: 60s  

binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence
      on_press:
        - light.turn_on:
            id: led_ID
            red: 0
            green: 100%
            blue: 0
      on_release:
        - light.turn_on:
            id: led_ID
            red: 0
            green: 0
            blue: 100%
select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode

number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum
    # See "Number" section below for detail
    gate_select:
      name: Select Gate to Set
    still_threshold:
      name: Set Still Threshold Value
    move_threshold:
      name: Set Move Threshold Value
      
button:
  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits
  - platform: restart
    name: restart
    entity_category: diagnostic

light:
  - platform: neopixelbus
    variant: ws2812
    id: led_ID
    num_leds: 1
    pin: 8