substitutions:
  tank_height: 100
  full_tank_height: 10

  relay_1_pin: 10
  relay_2_pin: 13
  relay_3_pin: 15
  buzzer_pin: 2
  led_pin: 16
  sda_pin: 4
  scl_pin: 5
  srx_pin: 12
  stx_pin: 14
  button_pin: 0
  mode_pin: 3

esphome:
  name: wtlc
  friendly_name: WTLC
  project:
    name: "MDtronix.WTLC"
    version: "HW v9.0"
  on_boot:
    priority: 800
    then:
      - display.page.show: oled_splash_page
      - delay: 5s
      - display.page.show: oled_level_page
      - if:
          condition:
            lambda: 'return id(mode_id).state && id(water_level_id).state >= id(stop_pump_id).state;'
          then:
            - switch.turn_off: pump_id
    
esp8266:
  board: esp12e
  restore_from_flash: true

logger:
debug:
api:
ota:
  - platform: esphome
    on_progress: 
      then:
        - lambda: |-
            id(ota_progress) = x;  // store progress percentage
            id(oled_id).update();
        - display.page.show: oled_ota_page
        
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}
  fast_connect: true
  # manual_ip: 
  #   static_ip: 192.168.0.128
  #   gateway: 192.168.0.1
  #   subnet: 255.255.255.0
  on_connect:
    then:
      if:
        condition:
          switch.is_on: pump_id
        then:
          - light.turn_on: led_id
        else:
          - light.turn_off: led_id

captive_portal:
web_server:

uart:
  baud_rate: 9600
  rx_pin: $srx_pin
  id: sensor_uart_id

i2c:
  id: i2c_id
  scan: True

globals:
  - id: ota_progress
    type: float
    restore_value: no
    initial_value: '0'

image:
  - file: "MDtronix_black.png"
    id: mdtronix_logo
    resize: 128x64
    type: binary

font:
  - file: "gfonts://Roboto"
    id: font1
    size: 12

display: !include WTLC/display.yaml

sensor:
  - !include WTLC/sensors.yaml
        
  - platform: template
    id: water_level_id
    accuracy_decimals: 0
    unit_of_measurement: '%'
    update_interval: 1s
    name: Level
    lambda: |-
      int level = map(id(sensor_id).state, ${tank_height}, ${full_tank_height}, 0, 100);
      if (level < 0) level = 0;
      if (level > 100) level = 100;
      return level;
    filters:
      - throttle: 1s      # Update every 1 second
      - median:           # Smooth out noise
          window_size: 7
          send_every: 3
          send_first_at: 1  
    on_value:
      then:
        - if:
            condition:
              switch.is_on: mode_id
            then:
              - if:
                  condition:
                    lambda: 'return (id(water_level_id).state <= id(start_pump_id).state) && !id(pump_id).state;'
                  then:
                    - switch.turn_on: pump_id
                    - logger.log: "Water level reached start threshold, turning on pump."
        
              - if:
                  condition:
                    lambda: 'return id(water_level_id).state >= id(stop_pump_id).state;'
                  then:
                    - switch.turn_off: pump_id
                    - logger.log: "Water level reached stop threshold, turning off pump."
        - lambda: |-
            id(oled_id).update();

  
number:
  - platform: template
    name: "Start Pump at"
    id: start_pump_id
    optimistic: true
    restore_value: yes
    min_value: 10
    max_value: 50
    step: 10
    unit_of_measurement: "%"
    icon: "mdi:water-check"
    initial_value: 10
    entity_category: 'config'
            
  - platform: template
    name: "Stop Pump at"
    id: stop_pump_id
    optimistic: true
    restore_value: True
    min_value: 70
    max_value: 100
    step: 10
    unit_of_measurement: "%"
    icon: "mdi:water-check"
    initial_value: 100    
    entity_category: "config"

button:
  - platform: restart
    name: Restart
    id: restart_id
    entity_category: "diagnostic"

  # - platform: factory_reset
  #   name: Factory Reset
  #   id: factory_reset_id
  #   entity_category: 'diagnostic'

switch:
  - platform: gpio
    id: pump_id
    name: Pump
    icon: mdi:pump
    pin:
      number: $relay_1_pin
    restore_mode: RESTORE_DEFAULT_OFF      
    on_turn_on: 
      then:
        - light.turn_on: led_id
    on_turn_off: 
      then:
        - light.turn_off: led_id

  - platform: template
    id: mode_id
    name: Automatic Mode
    icon: mdi:flash-auto
    optimistic: True
    restore_mode: RESTORE_DEFAULT_OFF
    # entity_category: 'config'

  - platform: template
    id: dryrun_id
    optimistic: True
    name: DryRun
    icon: mdi:water-remove
    restore_mode: RESTORE_DEFAULT_ON    
    entity_category: 'config'

light:
  - platform: status_led
    id: led_id
    pin: 
      number: $led_pin
      inverted: False

binary_sensor:
  - platform: gpio
    pin: 
      number: $mode_pin
      mode: INPUT_PULLUP
      inverted: True
    id: mode_button_id
    on_press:
      then:
        - switch.toggle: mode_id
  - platform: gpio
    id: pump_on_id
    pin:
      number: $button_pin
      mode: INPUT_PULLUP
      inverted: True
    on_press: 
      then:
        - switch.toggle: pump_id

text_sensor:
  - platform: debug
    reset_reason:
      name: "Reset Reason"

time:
  - platform: sntp
    id: sntp_time
    timezone: "Asia/Kolkata"      