substitutions:
  tank_height: 100
  full_tank_height: 10

packages:
  pins: !include WTLC/pins.yaml
  base: !include WTLC/base.yaml
  sensors: !include WTLC/sensors.yaml
  switches: !include WTLC/switches.yaml

preferences:
  flash_write_interval: 5min

globals:
  - id: ota_progress
    type: float
    restore_value: no
    initial_value: '0'

image:
  - file: "MDtronix_black.png"
    id: mdtronix_logo
    resize: 128x64
    type: binary

font:
  - file: "gfonts://Roboto"
    id: font1
    size: 12

display: !include WTLC/display.yaml

sensor:
  - platform: template
    id: water_level_id
    accuracy_decimals: 0
    unit_of_measurement: '%'
    update_interval: 1s
    icon: mdi:water-percent
    name: Level
    lambda: |-
      int level = map(id(sensor_id).state, ${tank_height}, ${full_tank_height}, 0, 100);
      if (level < 0) level = 0;
      if (level > 100) level = 100;
      return level;
    filters:
      - throttle: 1s      # Update every 1 second
      - median:           # Smooth out noise
          window_size: 7
          send_every: 3
          send_first_at: 1
    on_value:
      then:
        - component.update: oled_id
    on_value_range:
      - below: !lambda 'return id(start_pump_id).state;'
        then:
          - logger.log: "Water level below start threshold, turning ON pump."
      - above: !lambda 'return id(stop_pump_id).state;'
        then:
          - logger.log: "Water level above stop threshold, turning OFF pump."
number:
  - platform: template
    name: "Start Pump at"
    id: start_pump_id
    optimistic: true
    restore_value: yes
    min_value: 10
    max_value: 50
    step: 10
    unit_of_measurement: "%"
    icon: "mdi:water-check"
    initial_value: 10
    entity_category: 'config'
            
  - platform: template
    name: "Stop Pump at"
    id: stop_pump_id
    optimistic: true
    restore_value: True
    min_value: 70
    max_value: 100
    step: 10
    unit_of_measurement: "%"
    icon: "mdi:water-check"
    initial_value: 100    
    entity_category: "config"

button:
  - platform: restart
    name: Restart
    id: restart_id
    entity_category: "diagnostic"

binary_sensor:
  - platform: gpio
    pin: 
      number: $mode_pin
      mode: INPUT_PULLUP
      inverted: True
    id: mode_button_id
    on_press:
      then:
        - switch.toggle: mode_id
  - platform: gpio
    id: pump_on_id
    pin:
      number: $button_pin
      mode: INPUT_PULLUP
      inverted: True
    on_press: 
      then:
        - switch.toggle: pump_id