esphome:
  name: wtcl-test
  friendly_name: WTCL test

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

captive_portal:
web_server:
  version: 3

uart:
  baud_rate: 9600
  rx_pin: 13
  id: serial_id

sensor:
  - platform: a02yyuw
    name: "Ultrasonic Distance"
    id: distance_sensor
    uart_id: serial_id
    unit_of_measurement: "cm"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1       # convert mm → cm
      - lambda: |-
          if (x < 0) return NAN;  // ignore invalid readings
          return x;