esphome:
  name: "wtlc-test"
  friendly_name: wtlc test
  min_version: 2025.9.0
  name_add_mac_suffix: false
  on_boot:
    - priority: 800
      then:
        - display.page.show: oled_splash_page
    - priority: -100
      then:
        - display.page.show: oled_hello

esp8266:
  board: esp12e

# Enable logging
logger:
debug:
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  ap: {}
  # power_save_mode: HIGH

web_server:

i2c:
  sda: 04
  scl: 05
  frequency: 100khz

globals:
  - id: splash_flag
    type: bool
    restore_value: no
    initial_value: 'true'

interval:
  - interval: 5s
    then:
      - globals.set:
          id: splash_flag
          value: 'false'    

font:
  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: roboto_16
    size: 16

image:
  - file: "MDtronix_black.png"
    id: logo_black
    resize: 128x64
    type: binary

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: oled_id
    address: 0x3C
    pages:
      - id: oled_splash_page
        lambda: |-
          uint8_t x = (it.get_width() - id(logo_black).get_width()) / 2;
          uint8_t y = (it.get_height() - id(logo_black).get_height()) / 2;
          it.image(x, y, id(logo_black));

      - id: oled_hello
        lambda: |-
          it.print(0, 0, id(roboto_16), "Hello World!");