esphome:
  name: wtlc
  friendly_name: WTLC
  project:
    name: "MDtronix.WTLC"
    version: "HW v9.0"
  on_boot:
    priority: 800
    then:
      - display.page.show: oled_splash_page
      - delay: 5s
      - display.page.show: oled_level_page
      # - componant.update: pump_id
      - if:
          condition:
            lambda: 'return id(mode_id).state && id(water_level_id).state >= id(stop_pump_id).state;'
          then:
            - switch.turn_off: pump_id
    
esp8266:
  board: esp12e
  restore_from_flash: true

logger:
debug:
api:
  max_connections: 10
ota:
  - platform: esphome
    on_progress: 
      then:
        - lambda: |-
            id(ota_progress) = x;  // store progress percentage
            id(oled_id).update();
        - display.page.show: oled_ota_page
        
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}
  fast_connect: true
  # manual_ip: 
  #   static_ip: 192.168.0.128
  #   gateway: 192.168.0.1
  #   subnet: 255.255.255.0
  on_connect:
    then:
      if:
        condition:
          switch.is_on: pump_id
        then:
          - light.turn_on: led_id
        else:
          - light.turn_off: led_id

captive_portal:
web_server:

uart:
  baud_rate: 9600
  rx_pin: $srx_pin
  id: sensor_uart_id

i2c:
  id: i2c_id
  scan: True

light:
  - platform: status_led
    id: led_id
    pin: 
      number: $led_pin
      inverted: False

text_sensor:
  - platform: debug
    reset_reason:
      name: "Reset Reason"

time:
  - platform: sntp
    id: sntp_time
    timezone: "Asia/Kolkata"            